version: '3'
services:
    docker:
        privileged: true
        image: docker:dind
        environment: 
            - DOCKER_TLS_CERTDIR=/certs
        volumes: 
            - jenkins-docker-certs:/certs/client
            - ./jenkins_home:/var/jenkins_home 
        ports: 
            - 2376:2376
        networks: 
            - jenkinsnet
        restart: always
    jenkins:
        privileged: true
        user: root
        image: myjenkins
        container_name: jenkins
        build: ./jenkins
        environment: 
            - DOCKER_HOST=tcp://docker:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
        volumes: 
            - jenkins-docker-certs:/certs/client:ro
            - ./jenkins_home:/var/jenkins_home 
        ports: 
            - 8080:8080
            - 50000:50000
        networks: 
            - jenkinsnet
        restart: always
    server:
        image: nginx:1.17.2
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf # your nginx config file
            - /var/log/nginx:/var/log/nginx # log files
        restart: always
        command: nginx-debug -g 'daemon off;'
        ports:
            - 8000:80
        networks:
            - jenkinsnet
        depends_on: 
            - jenkins
        restart: always
networks: 
    jenkinsnet:     
volumes:
    jenkins-docker-certs: