version: '3'
services:
    docker:
        privileged: true
        image: docker:dind
        environment: 
            - DOCKER_TLS_CERTDIR=/certs
        volumes: 
            - jenkins-docker-certs:/certs/client
            - ./jenkins_home:/var/jenkins_home 
        ports: 
            - 2376:2376
        networks: 
            - jenkins
    jenkins:
        image: myjenkins
        container_name: jenkins
        build: ./jenkins
        environment: 
            - DOCKER_HOST=tcp://docker:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
        volumes: 
            - jenkins-docker-certs:/certs/client:ro
            - ./jenkins_home:/var/jenkins_home 
        ports: 
            - 8080:8080
            - 50000:50000
        networks: 
            - jenkins

networks: 
    jenkins:  
    
volumes:
    jenkins-docker-certs: